import os
import sys
import glob
import re

def audit_codebase():
    print("=== GLOBAL LATEX CODEBASE AUDIT (1:1 PROTOCOL) ===")
    errors = []
    warnings = []
    
    tex_files = sorted(glob.glob("tex/*.tex"))
    print(f"[1/4] Syntax and compliance analysis across {len(tex_files)} TEX files in 'tex/'...")
    
    forbidden_patterns = [
        (r'\\makecell', "Use of \\makecell not natively supported across all tabular layouts"),
        (r'tcolorbox.*colback=[^w]', "Colored tcolorbox backgrounds prohibited under 1:1 Protocol"),
        (r'AI signature|Generated by AI|ChatGPT|Anthropic|Gemini|Claude', "AI signatures or meta-commentary detected in code"),
    ]
    
    available_figures = set(os.path.basename(f) for f in glob.glob("figures/*.*"))
    
    for tf in tex_files:
        with open(tf, "r", encoding="utf-8") as f:
            content = f.read()
            
        if "\\documentclass[../main.tex]{subfiles}" not in content:
            warnings.append(f"{tf}: Missing header \\documentclass[../main.tex]{subfiles}")
        if "\\begin{document}" not in content or "\\end{document}" not in content:
            errors.append(f"{tf}: Missing \\begin/\\end document structure")
            
        for pattern, msg in forbidden_patterns:
            if re.search(pattern, content, re.IGNORECASE):
                errors.append(f"{tf}: {msg}")
                
        img_matches = re.findall(r'\\includegraphics(?:\[.*?\])?\{([^}]+)\}', content)
        for img in img_matches:
            img_name = os.path.basename(img)
            if img_name not in available_figures:
                errors.append(f"{tf}: Figure not found in 'figures/': '{img}'")
                
    print("[2/4] Checking master file main.tex...")
    main_path = "main.tex" if os.path.exists("main.tex") else ("templates/main.tex" if os.path.exists("templates/main.tex") else None)
    if main_path:
        if main_path == "templates/main.tex" and len(tex_files) == 0:
            print(f"  [INFO] Using master template '{main_path}' (clean/initial repository state).")
        with open(main_path, "r", encoding="utf-8") as mf:
            main_content = mf.read()
            for tf in tex_files:
                base_tf = os.path.splitext(os.path.basename(tf))[0]
                if f"\\subfile{{tex/{base_tf}}}" not in main_content:
                    warnings.append(f"File '{tf}' is not included or is commented out in {main_path}")
    else:
        errors.append("Master file 'main.tex' or 'templates/main.tex' missing from repository!")
        
    print("[3/4] Checking compilation logs...")
    if os.path.exists("main.log"):
        with open("main.log", "r", encoding="utf-8", errors="ignore") as lf:
            log_text = lf.read()
            if "Fatal error" in log_text or "Emergency stop" in log_text:
                errors.append("main.log indicates a fatal error during the last compilation.")
                
    print("\n=== AUDIT RESULTS ===")
    if not errors and not warnings:
        print("[OK] NO ERRORS DETECTED! Codebase is 100% sound, compliant with the 1:1 Protocol, and production-ready.")
    else:
        if warnings:
            print(f"\n[WARNINGS] ({len(warnings)}):")
            for w in warnings:
                print(f"  - {w}")
        if errors:
            print(f"\n[CRITICAL ERRORS] ({len(errors)}):")
            for e in errors:
                print(f"  - {e}")
            return False
            
    return len(errors) == 0

if __name__ == "__main__":
    success = audit_codebase()
    sys.exit(0 if success else 1)
